image: node:10.15.3

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    release-:
      - step:
          caches:
            - node
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r application.zip .
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $ADMIN_APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: "upload"
                ZIP_FILE: "application.zip"
                VERSION_LABEL: "my-app-5.0.0"
            - pipe: atlassian/aws-code-deploy:0.2.10
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $ADMIN_APPLICATION_NAME
                DEPLOYMENT_GROUP: $ADMIN_DEV_DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: "deploy"
                WAIT: "true"
                VERSION_LABEL: "my-app-5.0.0"
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
